import { describe, expect, it, vi } from 'vitest';

import { HOURLY_ARCHIVE_VALIDATOR_BATCH_SIZE, HourlyArchiveStorage } from './hourlyArchive.js';

// This helper renders the captured Prisma SQL template into readable text for assertions.
function renderSql(strings: TemplateStringsArray, values: unknown[]): string {
  return strings.reduce((sql, chunk, index) => {
    const value = values[index];
    const renderedValue =
      value &&
      typeof value === 'object' &&
      'strings' in value &&
      Array.isArray((value as { strings: unknown }).strings)
        ? (value as { strings: string[] }).strings.join('?')
        : '?';

    return sql + chunk + (index < values.length ? renderedValue : '');
  }, '');
}

// This suite verifies resource-friendly hourly archive database writes.
describe('HourlyArchiveStorage', () => {
  // This test verifies hourly aggregation is split by validator ranges.
  it('archives an hour in validator batches', async () => {
    // This value simulates the highest validator id present in the database.
    const maxValidatorIndex = 100001;

    // This list records every raw SQL call made inside the archive transaction.
    const rawCalls: string[] = [];

    // This transaction client captures SQL and simulates a validator table larger than one batch.
    const tx = {
      $executeRawUnsafe: vi.fn().mockResolvedValue(undefined),
      $executeRaw: vi.fn((strings: TemplateStringsArray, ...values: unknown[]) => {
        rawCalls.push(renderSql(strings, values));
        return Promise.resolve(undefined);
      }),
      $queryRaw: vi.fn().mockResolvedValue([{ max_idx: maxValidatorIndex }]),
      archive: {
        update: vi.fn().mockResolvedValue(undefined),
      },
    };

    // This prisma stub runs the interactive transaction callback with the mocked transaction.
    const prisma = {
      $transaction: vi.fn(async (callback: (transaction: typeof tx) => Promise<void>) => {
        await callback(tx);
      }),
    };

    // This storage instance executes the real archive method against the prisma stub.
    const storage = new HourlyArchiveStorage(prisma as never);

    // This call archives one hour and should split aggregation across validator ranges.
    await storage.archiveHourAtomically(
      new Date('2025-12-16T13:00:00.000Z'),
      100,
      200,
      10,
      20,
      5,
      'validator_hourly_archive_2025121613',
      'committee_100-200',
      'epoch_rewards_10-20',
    );

    // This filter keeps only the heavyweight archive INSERT statements.
    const insertCalls = rawCalls.filter((sql) =>
      sql.includes('INSERT INTO validator_hourly_archive'),
    );

    // This value mirrors the inclusive batch loop used by hourly archive storage.
    const expectedInsertCount =
      Math.floor(maxValidatorIndex / HOURLY_ARCHIVE_VALIDATOR_BATCH_SIZE) + 1;

    // This assertion verifies one INSERT is executed per validator batch.
    expect(insertCalls).toHaveLength(expectedInsertCount);

    // This assertion verifies the batch loop is driven by validator cardinality.
    expect(tx.$queryRaw).toHaveBeenCalledTimes(1);
  });

  // This test verifies hourly archive reads the exact raw partitions being archived.
  it('aggregates from child raw partitions instead of partitioned parent tables', async () => {
    // This list records every parameterized SQL statement generated by the archive transaction.
    const rawCalls: string[] = [];

    // This transaction client captures the archive SQL while keeping the batch loop to one pass.
    const tx = {
      $executeRawUnsafe: vi.fn().mockResolvedValue(undefined),
      $executeRaw: vi.fn((strings: TemplateStringsArray, ...values: unknown[]) => {
        rawCalls.push(renderSql(strings, values));
        return Promise.resolve(undefined);
      }),
      $queryRaw: vi.fn().mockResolvedValue([{ max_idx: 0 }]),
      archive: {
        update: vi.fn().mockResolvedValue(undefined),
      },
    };

    // This prisma stub runs the real archive transaction against the mocked transaction client.
    const prisma = {
      $transaction: vi.fn(async (callback: (transaction: typeof tx) => Promise<void>) => {
        await callback(tx);
      }),
    };

    // This storage instance receives real partition names from the partition controller contract.
    const storage = new HourlyArchiveStorage(prisma as never);

    // This call archives the same hourly raw partitions that will be dropped at the end.
    await storage.archiveHourAtomically(
      new Date('2026-06-28T17:00:00.000Z'),
      14653504,
      14653798,
      457922,
      457931,
      5,
      'validator_hourly_archive_2026062817',
      'committee_14653504-14653798_2026062817',
      'epoch_rewards_457922-457931_2026062817',
    );

    // This statement is the long-running aggregation that must avoid locking raw parent tables.
    const archiveInsertSql = rawCalls.find((sql) =>
      sql.includes('INSERT INTO validator_hourly_archive'),
    );

    // The aggregation should scan the committee child partition for the archived hour.
    expect(archiveInsertSql).toContain('FROM "committee_14653504-14653798_2026062817" c');

    // The aggregation should scan the epoch_rewards child partition for the archived hour.
    expect(archiveInsertSql).toContain('FROM "epoch_rewards_457922-457931_2026062817"');

    // The aggregation must not scan the partitioned parent table during the long transaction.
    expect(archiveInsertSql).not.toContain('FROM committee c');

    // The aggregation must not scan the epoch_rewards parent during the long transaction.
    expect(archiveInsertSql).not.toContain('FROM epoch_rewards');
  });
});
