import type { BeaconTime } from '@beacon-indexer/beacon-utils/beaconTime';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { createActor } from 'xstate';

import { lagAlertingMachine } from './lagAlerting.machine.js';

import type { SlotController } from '@/src/services/consensus/controllers/slot.js';

const telegramMocks = vi.hoisted(() => ({
  sendTelegramAlert: vi.fn().mockResolvedValue(undefined),
}));

// Stub Telegram delivery so the test can inspect the rendered alert body.
vi.mock('@/src/lib/telegram.js', () => telegramMocks);

// Stub logging so the test verifies only lag alert behavior.
vi.mock('@/src/xstate/pinoLog.js', () => ({
  pinoLog: vi.fn(() => () => {}),
}));

describe('lagAlertingMachine', () => {
  afterEach(() => {
    // Restore real timers so this file does not affect other test suites.
    vi.useRealTimers();

    // Reset all mocks so each scenario starts with clean call history.
    vi.restoreAllMocks();
  });

  it('sends lag alerts with slot distance and without the error log tail', async () => {
    // Use fake timers so the five-minute polling interval runs immediately.
    vi.useFakeTimers();

    // Return a processed slot far enough behind the head to trigger an alert.
    const slotController = {
      getLastProcessedSlot: vi.fn().mockResolvedValue(900),
    } as unknown as SlotController;

    // Expose BeaconTime methods used by the machine and distance calculation.
    const beaconTime = {
      getChainCurrentSlot: vi.fn(() => 1001),
      getLookbackSlot: vi.fn(() => 0),
      getTimestampFromSlotNumber: vi.fn((slot: number) => slot * 12_000),
    } as unknown as BeaconTime;

    // Start the machine with the minimum input needed for one lag check.
    const actor = createActor(lagAlertingMachine, {
      input: {
        slotController,
        beaconTime,
        chain: 'ethereum',
      },
    });

    actor.start();

    // Advance one scheduled check so the lag alert path executes.
    await vi.advanceTimersByTimeAsync(5 * 60 * 1000);

    // Wait until the invoked alert actor calls the Telegram boundary.
    await vi.waitFor(() => {
      expect(telegramMocks.sendTelegramAlert).toHaveBeenCalledTimes(1);
    });

    // Read the Telegram message generated by the alert actor.
    const message = telegramMocks.sendTelegramAlert.mock.calls[0]?.[0];

    // Confirm the alert shows the slot lag and derived wall-clock distance.
    expect(message).toContain('Lag: <b>101 slots</b>');
    expect(message).toContain('Distance: <b>00:20:12</b>');

    // Confirm the alert no longer includes errors-latest log content.
    expect(message).not.toContain('error log');
    expect(message).not.toContain('<pre>');

    actor.stop();
  });
});
