name: indexer-monitoring-spike

services:
  loki:
    image: grafana/loki:3.1.1
    command: -config.file=/etc/loki/config.yml
    ports:
      - '33100:3100'
    volumes:
      - ./loki/loki.yml:/etc/loki/config.yml:ro

  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=2h
    ports:
      - '39090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.1.5
    ports:
      - '3300:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - loki
      - prometheus

  mock-log-generator:
    build:
      context: ./mock-log-generator
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - METRICS_PORT=9100
    ports:
      - '39100:9100'
    depends_on:
      - loki
